package com.gavelier.gavelierplus.domain;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "buyers")
public class Buyer implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private String id;

    @NotNull
    @NotBlank
    private String auctionId;

    @Min(1)
    private int buyerNumber;

    @NotNull
    @NotBlank
    private String buyerName;
    
    private String buyerContactNumber;
    private String buyerAddress;

    public Buyer() {
    }


    public Buyer(String auctionId, int buyerNumber, String buyerName, String buyerContactNumber, String buyerAddress) {
        this.auctionId = auctionId;
        this.buyerNumber = buyerNumber;
        this.buyerName = buyerName;
        this.buyerContactNumber = buyerContactNumber;
        this.buyerAddress = buyerAddress;
    }

    public Buyer(String id, String auctionId, int buyerNumber, String buyerName, String buyerContactNumber, String buyerAddress) {
        this.id = id;
        this.auctionId = auctionId;
        this.buyerNumber = buyerNumber;
        this.buyerName = buyerName;
        this.buyerContactNumber = buyerContactNumber;
        this.buyerAddress = buyerAddress;
    }

    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "auctionId", globalSecondaryIndexName = "auctionId-index")
    public String getAuctionId() {
        return this.auctionId;
    }

    public void setAuctionId(String auctionId) {
        this.auctionId = auctionId;
    }

    @DynamoDBAttribute
    public int getBuyerNumber() {
        return this.buyerNumber;
    }

    public void setBuyerNumber(int buyerNumber) {
        this.buyerNumber = buyerNumber;
    }

    @DynamoDBAttribute
    public String getBuyerName() {
        return this.buyerName;
    }

    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName;
    }

    @DynamoDBAttribute
    public String getBuyerContactNumber() {
        return this.buyerContactNumber;
    }

    public void setBuyerContactNumber(String buyerContactNumber) {
        this.buyerContactNumber = buyerContactNumber;
    }

    @DynamoDBAttribute
    public String getBuyerAddress() {
        return this.buyerAddress;
    }

    public void setBuyerAddress(String buyerAddress) {
        this.buyerAddress = buyerAddress;
    }

    @Override
    public boolean equals(Object o) {
        if (o == this)
            return true;
        if (!(o instanceof Buyer)) {
            return false;
        }
        Buyer buyer = (Buyer) o;
        return Objects.equals(id, buyer.id) && Objects.equals(auctionId, buyer.auctionId) && buyerNumber == buyer.buyerNumber && Objects.equals(buyerName, buyer.buyerName) && Objects.equals(buyerContactNumber, buyer.buyerContactNumber) && Objects.equals(buyerAddress, buyer.buyerAddress);
    }


    @Override
    public String toString() {
        return "{" +
            " id='" + getId() + "'" +
            ", auctionId='" + getAuctionId() + "'" +
            ", buyerNumber='" + getBuyerNumber() + "'" +
            ", buyerName='" + getBuyerName() + "'" +
            ", buyerContactNumber='" + getBuyerContactNumber() + "'" +
            ", buyerAddress='" + getBuyerAddress() + "'" +
            "}";
    }

    

}