package com.gavelier.gavelierplus.domain;

import java.io.Serializable;
import java.math.BigDecimal;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "lots")
public class Lot implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    
    private String id;

    private String auctionId;

    private int sellerNumber;

    private int lotNumber;
    private String desc;
    private String estimate;
    private String reserve;

    private BigDecimal salePrice;

    private BigDecimal costToBuyer;
    private BigDecimal paymentToSeller;

    public Lot() {
    }

    public Lot(String id, String auctionId, int sellerNumber, int lotNumber, String desc, String estimate,
            String reserve, BigDecimal salePrice, BigDecimal costToBuyer, BigDecimal paymentToSeller) {
        this.id = id;
        this.auctionId = auctionId;
        this.sellerNumber = sellerNumber;
        this.lotNumber = lotNumber;
        this.desc = desc;
        this.estimate = estimate;
        this.reserve = reserve;
        this.salePrice = salePrice;
        this.costToBuyer = costToBuyer;
        this.paymentToSeller = paymentToSeller;
    }

    public Lot(String auctionId, int sellerNumber, int lotNumber, String desc, String estimate, String reserve,
            BigDecimal salePrice, BigDecimal costToBuyer, BigDecimal paymentToSeller) {
        this.auctionId = auctionId;
        this.sellerNumber = sellerNumber;
        this.lotNumber = lotNumber;
        this.desc = desc;
        this.estimate = estimate;
        this.reserve = reserve;
        this.salePrice = salePrice;
        this.costToBuyer = costToBuyer;
        this.paymentToSeller = paymentToSeller;
    }

    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @DynamoDBIndexHashKey(attributeName = "auctionId", globalSecondaryIndexName = "auctionId")
    public String getAuctionId() {
        return this.auctionId;
    }

    public void setAuctionId(String auctionId) {
        this.auctionId = auctionId;
    }

    @DynamoDBAttribute
    public int getSellerNumber() {
        return this.sellerNumber;
    }

    public void setSellerNumber(int sellerNumber) {
        this.sellerNumber = sellerNumber;
    }

    @DynamoDBAttribute
    public int getLotNumber() {
        return this.lotNumber;
    }

    public void setLotNumber(int lotNumber) {
        this.lotNumber = lotNumber;
    }

    @DynamoDBAttribute
    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    @DynamoDBAttribute
    public String getEstimate() {
        return this.estimate;
    }

    public void setEstimate(String estimate) {
        this.estimate = estimate;
    }

    @DynamoDBAttribute
    public String getReserve() {
        return this.reserve;
    }

    public void setReserve(String reserve) {
        this.reserve = reserve;
    }

    @DynamoDBAttribute
    public BigDecimal getSalePrice() {
        return this.salePrice;
    }

    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    @DynamoDBAttribute
    public BigDecimal getCostToBuyer() {
        return this.costToBuyer;
    }

    public void setCostToBuyer(BigDecimal costToBuyer) {
        this.costToBuyer = costToBuyer;
    }

    @DynamoDBAttribute
    public BigDecimal getPaymentToSeller() {
        return this.paymentToSeller;
    }

    public void setPaymentToSeller(BigDecimal paymentToSeller) {
        this.paymentToSeller = paymentToSeller;
    }

    @Override
    public String toString() {
        return "{" + " id='" + getId() + "'" + ", auctionId='" + getAuctionId() + "'" + ", sellerNumber='"
                + getSellerNumber() + "'" + ", lotNumber='" + getLotNumber() + "'" + ", desc='" + getDesc() + "'"
                + ", estimate='" + getEstimate() + "'" + ", reserve='" + getReserve() + "'" + ", salePrice='"
                + getSalePrice() + "'" + ", costToBuyer='" + getCostToBuyer() + "'" + ", paymentToSeller='"
                + getPaymentToSeller() + "'" + "}";
    }

}