package com.gavelier.gavelierplus.domain;

import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "sellers")
public class Seller implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private String id;

    @NotNull
    @NotBlank
    private String auctionId;

    @Min(1)
    private int sellerNumber;

    private String sellerName;
    private String sellerContactNumber;
    private String sellerAddress;

    public Seller() {
    }

    public Seller(String id, String auctionId, int sellerNumber, String sellerName,  String sellerContactNumber, String sellerAddress) {
        this.id = id;
        this.auctionId = auctionId;
        this.sellerNumber = sellerNumber;
        this.sellerName = sellerName;
        this.sellerContactNumber = sellerContactNumber;
        this.sellerAddress = sellerAddress;
    }

    public Seller(String auctionId, int sellerNumber, String sellerName, String sellerContactNumber, String sellerAddress) {
        this.auctionId = auctionId;
        this.sellerNumber = sellerNumber;
        this.sellerName = sellerName;
        this.sellerContactNumber = sellerContactNumber;
        this.sellerAddress = sellerAddress;
    }

    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "auctionId", globalSecondaryIndexName = "auctionId")
    public String getAuctionId() {
        return this.auctionId;
    }

    public void setAuctionId(String auctionId) {
        this.auctionId = auctionId;
    }

    @DynamoDBAttribute
    public int getSellerNumber() {
        return this.sellerNumber;
    }

    public void setSellerNumber(int sellerNumber) {
        this.sellerNumber = sellerNumber;
    }

    @DynamoDBAttribute
    public String getSellerName() {
        return this.sellerName;
    }

    public void setSellerName(String sellerName) {
        this.sellerName = sellerName;
    }

    @DynamoDBAttribute
    public String getSellerContactNumber() {
        return this.sellerContactNumber;
    }

    public void setSellerContactNumber(String sellerContactNumber) {
        this.sellerContactNumber = sellerContactNumber;
    }

    @DynamoDBAttribute
    public String getSellerAddress() {
        return this.sellerAddress;
    }

    public void setSellerAddress(String sellerAddress) {
        this.sellerAddress = sellerAddress;
    }

    @Override
    public boolean equals(Object o) {
        if (o == this)
            return true;
        if (!(o instanceof Seller)) {
            return false;
        }
        Seller sellers = (Seller) o;
        return Objects.equals(id, sellers.id) && Objects.equals(auctionId, sellers.auctionId) && sellerNumber == sellers.sellerNumber && Objects.equals(sellerContactNumber, sellers.sellerContactNumber) && Objects.equals(sellerAddress, sellers.sellerAddress);
    }

    @Override
    public String toString() {
        return "{" +
            " id='" + getId() + "'" +
            ", auctionId='" + getAuctionId() + "'" +
            ", sellerNumber='" + getSellerNumber() + "'" +
            ", sellerContactNumber='" + getSellerContactNumber() + "'" +
            ", sellerAddress='" + getSellerAddress() + "'" +
            "}";
    }


}